version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: location_service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "location_service"]
      interval: 10s
      retries: 5
      start_period: 10s

  grpc-server:
    restart: unless-stopped
    image: aliquamsiderea/userlocation_grpcserver
    build: .
    container_name: grpc-server
    ports:
      - "50051:50051"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: location_service
